### ISSUE TITLE
No map showing!!!

### ISSUE THREAD

**Issue by jowang0319** [AHAAAAAAA/PokemonGo-Map#1022]
I run the thing and no error showed up in terminal, but when I open localhost:5000, there's no map!!!

Just shown white web page with:"Flask Google Maps Full Map Example"words on it..

> [-] register_background_thread called
[-] register_background_thread: not running inside Flask so not starting thread
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
[-] register_background_thread called
[-] register_background_thread: initial registration
[+] Locale is en
 * Debugger is active!
[+] Getting initial location
[!] lat/long/alt: 40.8075 -73.9626 0
[!] PTC login for: jowang0319
 * Debugger pin code: 496-785-123
[+] RPC Session Token: TGT-3167400-miWbdt2wQLVMO ...
[+] Received API endpoint: https://pgorelease.nianticlabs.com/plfe/182/rpc
[+] Login successful
[+] Username: jowang0319
[+] You started playing Pokemon Go on: 2016-07-21 13:07:53
[+] POKECOIN: 0
[+] STARDUST: 100
[-] looping: step 1 of 100
[+] Searching for Pokemon at location 40.8075 -73.9626
Completed: 1.0%
[-] looping: step 2 of 100
[+] Searching for Pokemon at location 40.81 -73.9626
127.0.0.1 - - [21/Jul/2016 16:12:33] "GET / HTTP/1.1" 200 -
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 602, in process_request_thread
    self.handle_error(request, client_address)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 216, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 251, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 184, in execute
    write(data)
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 159, in write
    self.send_header('Server', self.version_string())
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 401, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe

127.0.0.1 - - [21/Jul/2016 16:12:33] "GET / HTTP/1.1" 200 -
Completed: 2.0%
[-] looping: step 3 of 100
[+] Searching for Pokemon at location 40.81 -73.9601
Completed: 3.0%
[-] looping: step 4 of 100
[+] Searching for Pokemon at location 40.8075 -73.9601
Completed: 4.0%
[-] looping: step 5 of 100
[+] Searching for Pokemon at location 40.805 -73.9601
Completed: 5.0%
[-] looping: step 6 of 100
[+] Searching for Pokemon at location 40.805 -73.9626
Completed: 6.0%
[-] looping: step 7 of 100
[+] Searching for Pokemon at location 40.805 -73.9651
Completed: 7.0%
[-] looping: step 8 of 100
[+] Searching for Pokemon at location 40.8075 -73.9651
Completed: 8.0%
[-] looping: step 9 of 100
[+] Searching for Pokemon at location 40.81 -73.9651
Completed: 9.0%
[-] looping: step 10 of 100
[+] Searching for Pokemon at location 40.8125 -73.9651
Completed: 10.0%
[-] looping: step 11 of 100
[+] Searching for Pokemon at location 40.8125 -73.9626
Completed: 11.0%
[-] looping: step 12 of 100
[+] Searching for Pokemon at location 40.8125 -73.9601
Completed: 12.0%
[-] looping: step 13 of 100
[+] Searching for Pokemon at location 40.8125 -73.9576
Completed: 13.0%
[-] looping: step 14 of 100
[+] Searching for Pokemon at location 40.81 -73.9576
Completed: 14.0%
[-] looping: step 15 of 100
[+] Searching for Pokemon at location 40.8075 -73.9576
Completed: 15.0%
[-] looping: step 16 of 100
[+] Searching for Pokemon at location 40.805 -73.9576
Completed: 16.0%
[-] looping: step 17 of 100
[+] Searching for Pokemon at location 40.8025 -73.9576
Completed: 17.0%
[-] looping: step 18 of 100

**Comment by Maxincredible52** [comment]
same here with the latest dev build

**Comment by DerScreever** [comment]
work like a charm:
http://85.214.145.87:5000/

**Comment by denniskai1234** [comment]
@DerScreever 

Still i got that bug where i have to refresh the site twice until i see the map.

**Comment by jowang0319** [comment]
@DerScreever  why is yours working !! that's crazy

**Comment by Maxincredible52** [comment]
i had to refresh 2 times, then the map did show eventually

**Comment by jowang0319** [comment]
@Maxincredible52  I refreshed several times.... doesn't work??

**Comment by Maxincredible52** [comment]
@jowang0319 i fixed this issue by explicitely deleting all cached data for the webpage i am running the map on and then it worked like a charm

**Comment by HinoReo** [comment]
I have cleared cache, but there's still no map. Hm..

**Comment by Valareos** [comment]
I have the same issue. Map does not show up, but as soon as I refresh, its all good

**Comment by jowang0319** [comment]
tried chrome safari and firefox.. tried clean cache... still doesn't work

**Comment by medghaim** [comment]
Closing this issue as it is outdated. If this issue still persists on the `develop` branch, please reopen a new issue and update the information therein to reflect the new changes.

Also, please be aware of the incredibly helpful and supportive community at: 
https://discordapp.com/invite/Kzp4yky
