### ISSUE TITLE
Scan step 2 failed. Response dictionary key error.

### ISSUE THREAD

**Issue by jhuberus** [AHAAAAAAA/PokemonGo-Map#2524]
So i have been using this for a few days now everything was working fine up until today been getting an issue that is listed below. Is there anyway to fix this? Or what might be causing this issue?

2016-07-28 20:32:16,884 [     search] [   INFO] Scanning step 1 of 271 started.
2016-07-28 20:32:16,884 [     search] [   INFO] Scanning step 2 of 271 started.
2016-07-28 20:32:16,888 [     search] [   INFO] Scanning step 3 of 271 started.
2016-07-28 20:32:16,888 [     search] [   INFO] Scanning step 4 of 271 started.
2016-07-28 20:32:16,891 [     search] [   INFO] Scanning step 5 of 271 started.
2016-07-28 20:32:17,115 [     search] [  ERROR] Scan step 2 failed. Response dictionary key error.
2016-07-28 20:32:17,134 [     search] [  ERROR] Scan step 4 failed. Response dictionary key error.
2016-07-28 20:32:17,140 [     search] [  ERROR] Scan step 3 failed. Response dictionary key error.

**Comment by kneel23** [comment]
see this issue thread #2513 
Speculation is they are throttling

**Comment by jhuberus** [comment]
Thanks i fixed the issue for now what i ended up doing was running (-st 10 -t 3) and it seems to be working just fine Scans a bit slower then i would like but not getting any errors as of yet.

**Comment by AHAAAAAAA** [comment]
Servers are under heavy load, not our code.

**Comment by IronChroni** [comment]
@AHAAAAAA unlikely - everything is green elsewhere, they are implementing a plethora of limiting tools including : rate limit per ip, requests per second, the failed steps happen with both ptc and google being up

**Comment by chuyskywalker** [comment]
That's entirely possible, but still not much can be done about that from this side.

**Comment by Shadowgar** [comment]
So if they are rendering the software unusable, wouldn't that be a major issue here? All of this work will go to waste if they throttle it without a work around.

**Comment by chuyskywalker** [comment]
Well, to be fair, by using this app you're probably breaking, like, 18 sections of the TOS you didn't _totally_ read and agreed to. It's their service, their servers, their game. While I, personally, don't think this map is harmful, we can't really tell 'em what to do :)

**Comment by kneel23** [comment]
Obviously its NOT server issues, and the issues coninue, it was throttling as was speculated.
