### ISSUE TITLE
PokemonGo-Map White Screen

### ISSUE THREAD

**Issue by shermsaludez** [AHAAAAAAA/PokemonGo-Map#2721]
## Expected Behavior
Should be able to display map

## Current Behavior
Running beehive.bat. ressults in white screen unable to access the map

http://imgur.com/a/h2Nh0

## Possible Solution
I heard something about grunt? I did that but it didn't work

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by Bitti09** [comment]
try  `grunt build`  it solved the problem for me

**Comment by shermsaludez** [comment]
@Bitti09 http://imgur.com/a/LR901 did i run this properly? I ran it in the PokemonGo Map folder. But i dont know if it's suppose to output this

**Comment by tkSimon** [comment]
Which version (read: commit) are you running? did you download as zip, or use git?

**Comment by shermsaludez** [comment]
@tkSimon  I downloaded PokemonGo as a zip file. Version 2.1.0

**Comment by Bitti09** [comment]
My output:

@vps:~/PokemonGo-Map# grunt build
Running "clean:build" (clean) task
>> 1 path cleaned.

Running "babel:dist" (babel) task

Running "uglify:build" (uglify) task
>> 4 sourcemaps created.
>> 4 files created.

Running "sass:dist" (sass) task

Running "cssmin:build" (cssmin) task
>> 2 files created. 49.46 kB → 36.03 kB

Done, without errors.


so it should work now for you

**Comment by shermsaludez** [comment]
@Bitti09 how would i fun @vps in command prompt? Do i need to download something to use that command? Sorry im pretty new

**Comment by tkSimon** [comment]
hm, i get the same thing when i do:
1. download and unzip https://github.com/AHAAAAAAA/PokemonGo-Map/releases/tag/v2.1.0
2. npm install
3. grunt build

**Comment by tkSimon** [comment]
not an expert on grunt though... (I <3 gulp) ... so won't be able to help with this one

**Comment by shermsaludez** [comment]
@tkSimon  argh im still getting the same output even after a clean download of the zip. Il be back later i have work :(

**Comment by shermsaludez** [comment]
@tkSimon  do i need to do anything else before running npm install and grunt build? Like the install -r requirements.txt

**Comment by shermsaludez** [comment]
@tkSimon  maybe you can send me your PokemonMap.zip with the grunt installed to me so that i can get it to work? :P

**Comment by neobithia** [comment]
When I run 

`grunt build`

I get

`'grunt' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by shermsaludez** [comment]
@neobithia  npm install

**Comment by neobithia** [comment]
@shermsaludez thanks!  How do we install that?

**Comment by tkSimon** [comment]
It's part of the nodejs package. If you have that installed already, just open a command prompt in the project directory and run `npm install`.
