### ISSUE TITLE
allow external change of location

### ISSUE THREAD

**Issue by Bart274** [AHAAAAAAA/PokemonGo-Map#3286]
## Expected Behavior
I'm using Home-Assistant to automate a lot at home. I would love to be able to use that to send my location to my Pokemon Go Map so it would get my next location to scan for pokemon from that. Is that possible? This might be done using MQTT or something else?

## Current Behavior
Now I need to open the map and change my location before it searches there. It would be great if I were to open the map and the scan is already done for my new location.

## Your Environment
* Version used: recent development version
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): server is running on Windows 10

**Comment by Highlander211288** [comment]
This already exists.  Use ngrok (or any similar service) to access the map from your mobile device, then select "Follow location" from the dropdown options menu.

**Comment by Bart274** [comment]
@Highlander211288 why should I need some service for this? I can already access the map externally, but using the Follow Location doesn't work... I keeps static at the location where it started and never changes...

**Comment by Highlander211288** [comment]
That's strange. What are you using for external access?

Some things to try in the meantime:

1. Make sure you have given GPS permissions to whatever program you are using for external access.
2. I don't think the Follow Location works if you are simply accessing your computer using Mobile Assistant.  I believe it will only work if you are accessing the map directly, which is why I suggested ngrok, which can provide a url for the map that you can access through  your phone's browser.

**Comment by Bart274** [comment]
I just forwarded my port on my router and when I use my external ip address followed by that port, I can see my map in safari on my iphone or in any browser on my pc at work...

**Comment by Highlander211288** [comment]
Huh. Should be working, then. But you can always try using a tunnel just in case. Sorry I couldn't be more help.

**Comment by Bart274** [comment]
what I think is weird, is that I was never asked if Safari could use the location of my iPhone for viewing that map, I would suspect it needs to do that first.

**Comment by itztq** [comment]
It depends on which browser you use.

For example: Im using my galaxy s6 with the chrome browser but the scan follow location or start at user location don't work with the browser.

But if i use it with the default browser of my s6 it works.

**Comment by drewreece** [comment]
Check your location services settings for Safari - if the app is not allowed to access your location you will not get a prompt from a site. I'd suggest you find another site to test that Safari is working correctly with location services - maps.google.com? Reset the browser if you can't get it working (in Settings app > Safari). Also try tapping the 'targeting icon', bottom right to see if it locates you. 

You could also post the command you are running, the -fl argument will cause the location to be static. I think it's possible to set that in the config too, so check that too.

I suspect you are being too optimistic to expect scanning to be done when you open the app, even with tracking it takes time. Safari doesn't send the location whilst powered off or backgrounded if I recall correctly.

**Comment by Bart274** [comment]
@itztq indeed, I think it could be the browser, in Firefox, the location was indeed used, in Google Chrome it didn't work.

@drewreecesomehow, the location services were disabled for Safari, I enabled them but the tracking still isn't working.
my config.ini looks like this:
```
auth-service:           ptc
username:               ***
password:               ***
location:               Gingelom
gmaps-key:              ***
host:                   0.0.0.0
```
the command I use to run my server is `runserver.py -dc`

**Comment by Bart274** [comment]
@drewreece actually, I think you misunderstood my question. when you change the location on the map you see this in the console:
```
2016-08-03 14:05:13,563 [       Thread-36][           app][    INFO] Changing next location: 50.8814437,4.5080561
2016-08-03 14:05:14,015 [   search_thread][        search][    INFO] New location caught, moving search grid
```
now what I was thinking was somehow be able to change the coordinates with something else (like MQTT) to change the location of the the search grid without opening the map first. So that as soon as you do open the map, the location is already changed and the search is already busy.

**Comment by drewreece** [comment]
Do you now have location services enabled & working in Safari now? Does it work for googlemaps?
 
I understand your question, I just don't think it will work as you expect. Safari seems to cease sending data on exit, so there is no possibility to have it change without running the map in the browser.

As far as I can see a POST submits a map change via the red drop pin (find it in the debug console). 
http://YOUR-IP:5000/next_loc?lat=00.000&lon=00.000
Work out how to submit that & you may be able to update it at will.

I admit that I do not know if the 'follow location' feature is intended to automatically move the scan areas or simply keep the map registered on where you are. I suspect the red drop pin is tied so that the scans are updated as location services sends erratic data (as it does on reconnection to PokemonGo app).

That's the best I can offer, you'll need a developer to clarify the purpose & function of that setting.

**Comment by Highlander211288** [comment]
As this issue has been resolved, I am closing the thread.
