### ISSUE TITLE
DecodeError: Unexpected end-group tag.

### ISSUE THREAD

**Issue by KatanaBoii** [AHAAAAAAA/PokemonGo-Map#415]
Windows 10, Python 2.7.0 

Shall the update of python solve my problem?

http://prnt.sc/buwpgu - log
thx

**Comment by Sejadis** [comment]
its just 2! reports below yours!
#412 
pls at least try to see if there is a solution before posting

**Comment by KatanaBoii** [comment]
Is it? Programm doesn't have any steps made

**Comment by AngryPelikan** [comment]
So, is there any solution for this?

**Comment by talentedmrripley** [comment]
@KatanaBoii try rerunning the pip install --upgrade -r requirements.txt.  And make sure you have the most recent version of the software.

**Comment by KatanaBoii** [comment]
@talentedmrripley ty, but it didn't help.

**Comment by crckdns** [comment]
it's basically ....servers says nope.

**Comment by inequity** [comment]
@Sejadis This is NOT the same issue as #412. Well, it sort of is, 412 was listing two issues, one of which was never resolved (this one). 

The issue resolved in 412 was that they had not gotten a new maps API key, so they were seeing the error in the webpage. The backend error of 'unexpected end-group tag' is a different issue entirely.

**Comment by inequity** [comment]
But your point about this being a duplicate does sort of stand, because this is the same issue as #344, #345, #353, #364, and probably more.

We should probably handle this error and print something more clear, along the lines of "Niantic server currently not handling requests", so people don't keep thinking it is an issue on their end.

**Comment by EarsKilla** [comment]
may be do auto reconnect to the servers and return in web requests something like "PokemonGo servers down :sob: "?

**Comment by benemorius** [comment]
We've been handling this exception since ~24 hours ago. Now it just prints the error and retries. Anyone still getting the crash in the opening post is running old code.

This issue can be closed along with any duplicates.

**Comment by brownsnake** [comment]
This issue is still affecting me, despite Niantic servers being up (I'm able to play right now with very little lag). Did they change the servers to deny the API calls completely?

**Comment by commanderjsoc** [comment]
Servers are down...http://downdetector.co.uk/problems/pokemon-go

**Comment by FrostTheFox** [comment]
@commanderjsoc http://go.jooas.com is a better source. Downdetector is community based, this link actually shows the server status.
