### ISSUE TITLE
ImportError: No module named peewee

### ISSUE THREAD

**Issue by boltron88** [AHAAAAAAA/PokemonGo-Map#718]
Receiving error
File "C:\\PokemonGo-Map-develop\pogom\models.py", line 5, in <module>
    from peewee import Model, SqliteDatabase, InsertQuery, IntegerField,\
ImportError: No module named peewee

### Environment info
Operating System: Windows 10 Pro x64

Installed version of Python: 2.7.12

### Steps to reproduce
1.  Download Dev build
2. run script runserver.py -a google -u *** -p *** -l "***" -st 10
3. see error

### What have you tried?
1. occurs with any variation of the script

**Comment by Valareos** [comment]
You need to rerun the installation. There are new modules the Dev build uses.  Run c:\Python27\Scripts\pip install --upgrade -r requirements.txt   from the command prompt within your pokemongo map folder

**Comment by jabelone** [comment]
The "automated" requirements installer refused to work for me.  I just ran the server, installed what was missing after reading the error and repeated that a few times.  Try running `pip install peewee`.

**Comment by boltron88** [comment]
Managed to get peewee sorted thanks to Valareos, next error is with credentials.json :( didn't have a single issue with the master branch lol

**Comment by jabelone** [comment]
What's the credentials error?  You have to rename the sample one to just "credentials.json".

**Comment by Valareos** [comment]
Ok, now with that one, they now requireing to get your own javascript api key.  https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key

You may either use the credentials.example.json file and rename, or use the -k API_KEY switch

**Comment by boltron88** [comment]
Yup, just sorted that thanks to the Wiki, but once again, a huge thank you for your help Valareos

**Comment by FrostTheFox** [comment]
All your issues are fixed?

**Comment by jabelone** [comment]
So is everything working ok now?

**Comment by jabelone** [comment]
@FrostTheFox hit send at the same time haha

**Comment by boltron88** [comment]
I had hoped so, but still getting KeyError: 'gmaps_key', 
my Credentials file looks like this 
	"ipastedmykeyhere" : ""
}

**Comment by jabelone** [comment]
It should actually look like this:

```
{
        "gmaps_key" : "paste-key-here"
}
```

**Comment by boltron88** [comment]
Ah, Thank you, Seems to be working correctly now, Thank you all so much for your help, revives my faith in humanity :)
