### ISSUE TITLE
OperationalError: database is locked

### ISSUE THREAD

**Issue by Bakies** [AHAAAAAAA/PokemonGo-Map#744]
Now the cause of this is probably because I am running 4 of these things at the same time from the same place but it seems like a simple fix: block until database file is ready to write 

might be able to manage a pull request if I start digging through the code tomorrow

This kills the scanning thread, flask stays alive
on dev branch 
commit 6022106cbbd4b0dc8d13839b52e6b31237d1f499

**Comment by Galtwise** [comment]
I have the same issue with 2 instances. Should be looked at

**Comment by HuntStarJonny** [comment]
same problem here

**Comment by Bakies** [comment]
I fixed this by catching the exception and retrying the query, doesnt seem like the cleanest solution but it looks like its working

**Comment by vaurdan** [comment]
Yup also happening with three instances running

**Comment by Bakies** [comment]
This is happening even if I isolate and instance and theres multiple (probably 3-5) people using it, when /raw_data gets hit a few times. I think this should be escalated to 'bug'

**Comment by TheReaperr** [comment]
@Bakies can you share your dirty fix please? I'm not very experienced in error handling and I can't figure out where I should be catching the exception. I just want to have a few scanlocations using the same map and I keep on running into this error

**Comment by Bakies** [comment]
My dirty fix was too dirty and does not fix, it eventually locks up completely

**Comment by TheReaperr** [comment]
Ah, that sucks. I really want a few scanning locations. I tried putting the one location in between me and my friends houses and increasing the radius, but it just takes way too long.

**Comment by vaurdan** [comment]
I believe I fixed it - at least temporarily - by increasing the sqlite connection timeout.

Here's the diff:

```diff
diff --git a/pogom/models.py b/pogom/models.py
index 08d77be..6b1e968 100644
--- a/pogom/models.py
+++ b/pogom/models.py
@@ -11,7 +11,7 @@ from .utils import get_pokemon_name
 from .transform import transform_from_wgs_to_gcj


-db = SqliteDatabase('pogom.db')
+db = SqliteDatabase('pogom.db',timeout=10)
 log = logging.getLogger(__name__)

```

**Comment by Bakies** [comment]
Yeah that should allow them to wait for connections longer, I will give it a try

**Comment by Galtwise** [comment]
Been testing this for 5m, so far so good

**Comment by Galtwise** [comment]
Still fails eventually. Can we build in some sort of retry on fail?

**Comment by HanYangZhao** [comment]
similar to #810 , the one of the posts suggest to "

> can you try changing line 14 on your models.py from db = SqliteDatabase('pogom.db') to db = SqliteDatabase('pogom.db', threadlocals=True), then delete pogom.db and run it again?

Seems to be working so far...

**Comment by HanYangZhao** [comment]
nop still locks up eventually

**Comment by hazanjon** [comment]
This happens consistently for me when searching my local city. A single search returns around 100~ pokestop locations and the upsert for this takes upto 10s. During this time any poll request from the map fails and throws a database is locked error.

**Comment by TheReaperr** [comment]
"Fixed" it by commenting in models.py:

#if pokestops:
      #   log.info("Upserting {} pokestops".format(len(pokestops)))
      #  bulk_upsert(Pokestop, pokestops)

Upserting those pokestops took way too long because in every cell it detected like 40 of em. Right now im running 5 scanners with 64 scans (-st 8). And they all take 3 minutes to finish scanning

**Comment by Galtwise** [comment]
So far this is working for me! I wonder if this may be a db size issue as well?

**Comment by vaurdan** [comment]
Ok, I'm solving this by adding the possibility to connect to a MySQL server instead of using sqlite. This is way better for advanced users like us that may want to run multiple instances with speed and without concurrency issues. 

I'll be opening a PR soon.

**Comment by billbo99** [comment]
how about running the collection and server/database as separate processes.
 
The user could start up multiple collection processes with different locations being set.  Each process would write to a collection folder with what they have discovered using the encounter_id as the filename.
 
The server/database process would poll the folder for new filenames and add the record into the DB then delete the file.
 
This way a single process writes to the SQLITE db and there wont be any locking issues.

**Comment by Galtwise** [comment]
Well, I wrapped the upsert section of models.py in a try/except and seem to not have further issues... Seems hacky, but it doesn't crash the instance
